/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.renan.desafiotroco.view;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import br.renan.desafiotroco.modelo.Caixa;
import br.renan.desafiotroco.modelo.Cedula;
import br.renan.desafiotroco.modelo.CemReais;
import br.renan.desafiotroco.modelo.CincoCentavos;
import br.renan.desafiotroco.modelo.CincoReais;
import br.renan.desafiotroco.modelo.CinquentaCentavos;
import br.renan.desafiotroco.modelo.CinquentaReais;
import br.renan.desafiotroco.modelo.DezCentavos;
import br.renan.desafiotroco.modelo.DezReais;
import br.renan.desafiotroco.modelo.Moeda;
import br.renan.desafiotroco.modelo.UmCentavo;
import br.renan.desafiotroco.modelo.UmReal;

/**
 *
 * @author Renan
 */
public class TelaTroco extends javax.swing.JFrame {

    private Caixa caixa;

    /**
     * Creates new form TelaTroco
     */
    public TelaTroco() {
        ArrayList<Moeda> moedas = new ArrayList<>();
        ArrayList<Cedula> cedulas = new ArrayList<>();

        moedas.add(new CinquentaCentavos());
        moedas.add(new DezCentavos());
        moedas.add(new CincoCentavos());
        moedas.add(new UmCentavo());

        cedulas.add(new CemReais());
        cedulas.add(new CinquentaReais());
        cedulas.add(new DezReais());
        cedulas.add(new CincoReais());
        cedulas.add(new UmReal());

        caixa = new Caixa(moedas, cedulas);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextValorASerPago = new javax.swing.JTextField();
        jTextValorPago = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCalcularTroco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelTroco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextValorASerPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextValorASerPagoKeyTyped(evt);
            }
        });

        jLabel1.setText("Valor do Pedido:");

        jLabel2.setText("Valor Pago:");

        jButtonCalcularTroco.setText("Calcular Troco");
        jButtonCalcularTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularTrocoActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelTroco.setText("Troco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCalcularTroco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextValorASerPago, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTroco)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValorASerPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonCalcularTroco))
                .addGap(31, 31, 31)
                .addComponent(jLabelTroco)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextValorASerPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextValorASerPagoKeyTyped
//        char c = evt.getKeyChar();
//        if(!(Character.isDigit(c)) 
//                || (c == KeyEvent.VK_BACK_SPACE)
//                || (c == KeyEvent.VK_DELETE)
//                || (c == KeyEvent.VK_COMMA)){
//            evt.consume();
//        }
    }//GEN-LAST:event_jTextValorASerPagoKeyTyped

    private void jButtonCalcularTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularTrocoActionPerformed
        jTextArea1.setText("");
        BigDecimal valorASerPago = BigDecimal.ZERO;
        BigDecimal valorPago = BigDecimal.ZERO;

        NumberFormat format = NumberFormat.getInstance(new Locale("pt", "BR"));

        try {
            if (jTextValorASerPago.getText().contains(",") || jTextValorPago.getText().contains(",")) {
                Number n1 = format.parse(jTextValorASerPago.getText());
                valorASerPago = BigDecimal.valueOf(n1.doubleValue());

                Number n2 = format.parse(jTextValorPago.getText());
                valorPago = BigDecimal.valueOf(n2.doubleValue());
                
            } else {
                double n1 = Double.parseDouble(jTextValorASerPago.getText());
                valorASerPago = BigDecimal.valueOf(n1);

                double n2 = Double.parseDouble(jTextValorPago.getText());
                valorPago = BigDecimal.valueOf(n2);
            }
        } catch (ParseException ex) {
            Logger.getLogger(TelaTroco.class.getName()).log(Level.SEVERE, null, ex);
        }

        caixa.setValorPedido(valorASerPago);
        caixa.setValorPago(valorPago);

        HashMap<String, Integer> contagemCedulasEMoedas = caixa.calcularQuantidadeCedulasEMoedas();
        if (caixa.getTroco().compareTo(BigDecimal.ZERO) > 0) {
            jTextArea1.append("Quantidade de Cédulas e Moedas: ");
            jLabelTroco.setText("Troco: " + caixa.formatarValor(caixa.getTroco()));
        } else if (caixa.getTroco().compareTo(BigDecimal.ZERO) == 0) {
            jTextArea1.append("Não há necessidade de troco");
        } else {
            jTextArea1.append("Falta dinheiro no pagamento");
        }

        contagemCedulasEMoedas.forEach((nomeMoeda, quantidade) -> {
            jTextArea1.append("\n" + quantidade + "x: " + nomeMoeda);
        });

    }//GEN-LAST:event_jButtonCalcularTrocoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTroco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularTroco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTroco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextValorASerPago;
    private javax.swing.JTextField jTextValorPago;
    // End of variables declaration//GEN-END:variables
}
